### ISSUE TITLE
Certain characters used as annotation (like U+30FC or U+3063) will throw off ruby alignment

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#124]
See ruby31.cap

**Comment by shimada-development** [comment]
See ruby33.cap

Known problem characters:
katakana letter small tu (U+30C3)
katakana letter small i (U+30A3)
rightwards arrow (U+2192)
leftwards arrow (U+2190)
hiragana letter small tu (U+3063)
katakana-hiragana prolonged sound mark (U+30FC)
katakana letter small a (U+30A1)

**Comment by skynavga** [comment]
The behavior described above is correct when using the default [Unicode UAX #14 Line Breaking Algorithm](http://www.unicode.org/reports/tr14/), which is the standard for TTML usage.

Some breaking behavior defined by UAX #14, such as with those characters in the Conditional Japanese (CJ) character class, e.g., small kana, may be variously treated as NS (non-starting) or ID (ideographic). The default ICU LB configuration specifies NS rather than ID, resulting in a stricter rather than looser breaking behavior, i.e., not permitting a break before.

Other characters included in the ruby33 and ruby34 tests fall into yet other UAX #14 categories, e.g., U+2190 and U+2192 arrows are in the AI (ambiguous ideographic) class, U+309B to U+309E and U+30FD to U+30FE kana sound and iteration marks are in the NS (non-starter) class. Depending on the previous character, a break may not be permitted by the default UAX #14 rules (as adopted in ICU 54).

We can readily reconfigure the ICU rules to support breaking before CJ (small kana) class, but doing so for AI and NS class requires non-standard customization, which is inadvisable. A work around for these latter cases is to explicitly include a U+200B ZERO WIDTH SPACE before the AI and NS class characters if a break is desired.

**Comment by skynavga** [comment]
Addressed in 184494cb6e2a0a653202a3a88930d19d12cf08fb.

**Comment by skynavga** [comment]
Another work around for ensuring spacing around AI (ambiguous ideographic) class characters is to use multiple ruby base / ruby text pairs rather than relying upon breaking behavior to pull apart ruby text characters that normally do not admit break before.
